version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/"
    groups:
      production-dependencies:
        dependency-type: production
        exclude-patterns:
          - "send" # Let's pretend that upgrading this dependency is causing non-trivial test failures
      development-dependencies:
        dependency-type: "development"
    schedule:
      interval: "daily"
